CREATE SEQUENCE autoIncrementClient  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE autoIncrementDevis  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE autoIncrementCommercial  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE autoIncrementProduit  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE autoIncrementDetailsDevis  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE autoIncrement  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;